export const AUTHENTICATE = 'AUTHENTICATE';
export const REFRESH_SESSION = 'REFRESH_SESSION';
export const SIGN_OUT = 'SIGN_OUT';
export const FETCH_RANDOM_CAT_SUCCESS = 'FETCH_RANDOM_CAT_SUCCESS';
export const FETCH_RANDOM_CAT_FAILURE = 'FETCH_RANDOM_CAT_FAILURE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const LOAD_FAVORITE = 'LOAD_FAVORITE';